### ISSUE TITLE
CRUD Dashboard user stories

### ISSUE THREAD

**Issue by IulianBogdan** [CSProjectsEAL/GraBID#18]
## 📋 User story
As a user I want to be able to create new dashboards, so that I can then view and edit them.

## Description
As a user I want to be able to create new dashboards by going to the sidebar menu selecting the correct icon. Then on a expandable sidemenu type in a unique name for the dashboard along with a description.

## User stories
1. As a user I want to be able to create a new dashboard.
1. As a user I want to be able to edit a dashboard
1. As a user I can view and  create new  queries 
1. As a user I want to combine a graph with data from queries and store it
1. As a user I want to view all graphs with data
1. As a user I want to be able to rearrange elements on a dashboard

## Acceptance Criteria

Mainflow: 
- [ ] As a user I want to be able to access the dashboard creation menu from the sidebar
- [ ] As a user I can then view a small dashboard creation menu on the sidebar menu that will expand in that same menu I need to be able to enter an optional description and a unique name.
- [ ] When I press the create button I will be send to a page where I can edit the dashboard, for now just make title and description editable.

- [ ] As a user I can view existing dashboards(by name) and when selected get send to a page where I can view, edit and delete it.
- [ ] As a user I can query data from Elasticsearch and view the query results, along with a slider to make it easy to adjust the timeslice so that I can use this data with a specific table.
- [ ] As a user I can edit the new dashboard by selecting.
- [ ] As user I can select from queries  customize the page
- [ ] As a user I can drag stored queries onto the dashboard and rearrange their placement.
